version: 2

jobs:
  dotnet:
    docker:
      - image: microsoft/dotnet-framework:3.5-runtime-windowsservercore-1709
    steps:
      - checkout

workflows:
  version: 2
  tests_and_docs:
    jobs:
      - dotnet
